### ISSUE TITLE
MindTouch community and resources

### ISSUE THREAD

**Issue by ymdahi** [LibreTexts/Libretext#151]
@Miniland1333 , @drdelmar , @ethanaturner 

Anyone know if there is any developer/user community for MindTouch? Apart from their support and documentation sites, I wonder if there are other organizations using MindTouch who have developers who might have insight/code to share.

**Comment by Miniland1333** [comment]
@drdelmar you should add him or ask him to be invited to the Mindtouch Slack channel. I'm not a part of that anymore so I can't do it.
