### ISSUE TITLE
Create API endpoint for `tags` & `info`

### ISSUE THREAD

**Issue by ymdahi** [LibreTexts/Libretext#159]
## Purpose
The ADAPT project makes use of the API endpoints to pull data from MT.  Currently, ADAPT uses the endpoint `/endpoint/contents/` to retreive properties like title, body, revision number; for example:

```
  $curl = curl_init();
/*example of a private page*/
$page_id = 346659;
$library = 'chem';
/*end example*/
curl_setopt_array($curl, [
  CURLOPT_FAILONERROR => true,
  CURLOPT_URL => "https://api.libretexts.org/endpoint/contents",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "PUT",
  CURLOPT_POSTFIELDS => '{"path":' . $page_id . ', "subdomain":"' . $library . '","mode": "view", "dreamformat":"json"}',
  CURLOPT_HTTPHEADER => [
    Origin: https://adapt.libretexts.org",
    Content-Type: text/plain"
  ],
]);
$response = curl_exec($curl);
```

We are extending the API to handle requests for the `info` and `tags` endpoints. These endpoints will allow us to query for:

- [ ] Author name (tags)
- [ ] License attribution (tags)
- [ ] User-friendly URLs (info)

#### Problem
These endpoints are available for public consumption - however that does not cover private or semi-private pages in MT. As such, we have to authenticate prior to making these calls. We can do so by building ontop of the existing authenticated endpoint `/contents/`.

## Proposed Solution
Extend the `/contents/` endpoint in endpoint.js, such that we can handle authentication for the new endpoints:
https://github.com/LibreTexts/Libretext/blob/636af9ae4cdab1d83e451ba853728400e08e9f6e/API/endpoint.js#L90-L116

## Relevents Links
* https://chem.libretexts.org/@go/page/346659
* https://chem.libretexts.org/@api/deki/pages/346659/contents?dream.out.format=json
* https://chem.libretexts.org/@api/deki/pages/346659/tags?dream.out.format=json

## MT Docs
* https://success.mindtouch.com/Integrations/API/API_Calls/pages/pages%2F%2F%7Bpageid%7D%2F%2Fcontents_(GET)
* https://success.mindtouch.com/Integrations/API/API_Calls/pages/pages%2F%2F%7Bpageid%7D%2F%2Ftags_(GET)

**Comment by ethanaturner** [comment]
Ground Control to Major @kreut
