### ISSUE TITLE
Create XML feed for ExLibris Ingest

### ISSUE THREAD

**Issue by ymdahi** [LibreTexts/Libretext#164]
## Purpose
Create a data point for Ex Libris to harvest Books from the LibreTexts libraries in order to make them discoverable in the Primo end-user search interface.

From email chain: "preparing [OAI-PMH](https://en.wikipedia.org/wiki/Open_Archives_Initiative_Protocol_for_Metadata_Harvesting) feeds will permit Ex Libris to complete the harvesting."

Although, we may be able to get started with just a simple XML Sitemap: from email chain: "We’ve worked with Ex Libris in the past to import sitemap files, and if you have or can get sitemap files for LibreTexts completed, then we can help make introductions at Ex Libris."

## MindTouch Sitemaps
As Ethan pointed out, MindTouch does auto-generate sitemaps for each library: 

* https://chem.libretexts.org/sitemap.xml
* https://chem.libretexts.org/sitemap_0.xml
* https://chem.libretexts.org/sitemap_1.xml

The issue is that these sitemaps do not have any additional data, such as: author(s), title, license, thumbnail, etc.. Also, we would probably need to separate out Books from Pages and be selected of which books to include.

## Possible Solutions
The team will meet with the UC Davis Library to discuss the available sitemaps and the next step forward.

Relevant Links:
* Example of book from OpenStax in Primo (this is the level of detail we need to provide): https://caccl-gcccd.primo.exlibrisgroup.com/discovery/fulldisplay?docid=cdi_openstax_books_978_1_947172_20_3&context=PC&vid=01CACCL_GROSSMONT:GROSSMONT&lang=en&search_scope=MyInst_and_CI&adaptor=Primo%20Central&tab=Everything&query=any,contains,openstax%20chemistry&mode=basic
*

**Comment by Miniland1333** [comment]
The Courses.json and Bookshelves.json files internally are derived from these sitemaps and contain a lot of the information that you are looking for.

https://github.com/LibreTexts/Libretext/blob/6e9964d81efb1c257b0d2bf695dad1735f36bfa4/nodePrint/nodePrint.js#L2024

**Comment by ethanaturner** [comment]
Resolved as of 03/29/2022.
