### ISSUE TITLE
Improving my documentation over winter break

### ISSUE THREAD

**Issue by Miniland1333** [LibreTexts/Libretext#167]
Let me know if there is any documentation for any pieces of my code that you would like me to improve over winter break. I have a bit of down time before the term starts.

**Comment by ymdahi** [comment]
Hey @Miniland1333 ! We will definitely take full advantage of this offer 😈 @drdelmar @ethanaturner : make sure to give Henry your laundary list here.

**Comment by ymdahi** [comment]
## Item #1: Analytics
Starting in the new year, we will be attempting to make the following update to the Analytics system:

- Build a "dashboard" app that will display aggregate analytics data in visualizations (e.g. a per-book chart that shows "Ave time spend on Page ABC")
- Replace .zip downloads with a JSON endpoint (or just CSVs) that can be queried/aggregated

As such, it would be great to have some docs/details about how the analytics system is currently set up. Specifically, I'm having a tough time figuring out where analytics.js is sending it's data and where the data that goes into the CSVs is coming from.

**Comment by ymdahi** [comment]
## Item 2: SSO/CAS

Any documentation for the CAS server would be great. Specifically a guide on adding services would be a huge help.

**Comment by Miniland1333** [comment]
> ## Item 1: Analytics
> Starting in the new year, we will be attempting to make the following update to the Analytics system:
> 
> * Build a "dashboard" app that will display aggregate analytics data in visualizations (e.g. a per-book chart that shows "Ave time spend on Page ABC")
> * Replace .zip downloads with a JSON endpoint (or just CSVs) that can be queried/aggregated
> 
> As such, it would be great to have some docs/details about how the analytics system is currently set up. Specifically, I'm having a tough time figuring out where analytics.js is sending it's data and where the data that goes into the CSVs is coming from.

To get you started, analytics.js sends the data to api.libretexts.org/ay which is here https://github.com/LibreTexts/Libretext/blob/master/API/analytics.js. The data is stored as files in analyticsdata

Since the current analytics system is quite basic and limited, it may be easier to just redo it. As-is, it lacks the database query features that a dashboard would want to gain different insights from the data.

**Comment by Miniland1333** [comment]
> ## Item 2: SSO/CAS
> Any documentation for the CAS server would be great. Specifically a guide on adding services would be a huge help.

The primary thing you will need to do is add a new service yaml file to https://github.com/LibreTexts/ApereoCAS/tree/main/etc/cas/LibreTexts/services

You likely will just find an existing service yaml file of the type you need (OAuthRegisteredService vs OidcRegisteredService), duplicate it, and then modify the fields as necessary. Once the file is pushed to Github, DigitalOcean App Platform will rebuild the application and launch it.

Documentation: https://apereo.github.io/cas/6.4.x/services/Service-Management.html

**Comment by Miniland1333** [comment]
Stale issue
