### ISSUE TITLE
VCell Issues

### ISSUE THREAD

**Issue by ymdahi** [LibreTexts/Libretext#194]
@Miniland1333 Sorry to bother you this way Henry, but there is an email from Henry J that needs your attn re: VCell. I'm not sure if you are still working on it or what might have changed since any recent updates, but it doesn't seem to be working for him anymore.

**Comment by Miniland1333** [comment]
I haven't made any updates since last week I don't think. I'll check it out later today once I get access to my Desktop.

**Comment by ymdahi** [comment]
Thanks Henry, this was, as you mention, an issue on VCell's side. It was promptly fixed by the VCell team. Thanks again.
