### ISSUE TITLE
Citation: Build Function

### ISSUE THREAD

**Issue by aryanrsuri** [LibreTexts/Libretext#38]
# buildcite(); function, 

- [x] modal
- [x] copy to clip
- [x] design updates
- [ ] RIS update

https://chem.libretexts.org/Under_Construction/Sandboxes/Student_Programmers/Aryan_Suri/Citation_Generator

**Comment by Miniland1333** [comment]
From Delmar, here are some additional subtasks:

- [ ] Implement copy to clipboard as you have done for Attribution
- [ ] Implement BibTeX and RIS file output types. These will be saved to the user's computer. [EXAMPLE](https://pubs.acs.org/action/showCitFormats?doi=10.1021%2Facs.biochem.8b01274&include=cit&format=ris&direct=true&downloadFileName=acs.biochem.8b01274&href=/doi/10.1021/acs.biochem.8b01274)
