### ISSUE TITLE
Citation Generator

### ISSUE THREAD

**Issue by Miniland1333** [LibreTexts/Libretext#4]
https://citation.js.org/
Create automatic citations on the page so that students can reference pages.
- [x] Create a new page for testing
- [x] Get citation.js workign with fixed JSOn
- [x] Populate JSOn from page information
- [ ] Feed response into user-friendly, aesthetically pleasing format
- [x] Incorporate citation button somewhere on page (perhaps near the social media/donation buttons?)

**Comment by niklundgren** [comment]
- [ ] Feed response into user-friendly, aesthetically pleasing format

- [ ] Incorporate citation button somewhere on page (perhaps near the social media/donation buttons?)

**Comment by Miniland1333** [comment]
TODO merged with above for tracking

**Comment by Miniland1333** [comment]
Added to social media bar with 5ccc140502664f83db24f6df7516ede3d7137d40
