### ISSUE TITLE
Update to Mathjax v3

### ISSUE THREAD

**Issue by aryanrsuri** [LibreTexts/Libretext#58]

**Comment by aryanrsuri** [comment]
update mathjax to current version

**Comment by Miniland1333** [comment]
Waiting for Mathjax v3 to support [automatic line breaks](http://docs.mathjax.org/en/latest/output/linebreaks.html).

**Comment by Miniland1333** [comment]
Mathjax still hasn't implemented this feature: https://docs.mathjax.org/en/latest/output/linebreaks.html

**Comment by Miniland1333** [comment]
Superceded by #222
