### ISSUE TITLE
License info on copy

### ISSUE THREAD

**Issue by Miniland1333** [LibreTexts/Libretext#6]
Opens a popup that will alert the user if they are attempting to copy content with a license on it.

- [x] - Capture Copy event
- [x] - Show an alert for testing
- [x] - Read page tags and get the license
- [x] - Only show up when a license is selected
- [x] - Show a final popup
- [x] - Include information in popup such as a breakdown or link to license full details.

**Comment by aryanrsuri** [comment]
Everything should be working well, just want to refine the alert messages
